name: flutter_clean_architecture
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  get_it: ^7.2.0
  dio: ^5.0.3
  equatable: ^2.0.5
  shared_preferences: ^2.0.20
  connectivity_plus: ^3.0.3
  permission_handler: ^10.2.0
  geolocator: ^9.0.2
  google_fonts: ^4.0.3
  animated_digit: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  mocktail: ^0.3.0
  value_listenable_test: ^0.0.1


flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/